version: "3.8"

services:
  backend1:
    build: .
    environment:
      - PORT=3000
    ports:
      - "3000:3000"

  backend2:
    build: .
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
