events {
    worker_connections 1024;
}

http {
    # Определение группы серверов для балансировки
    upstream backend_servers {
        # Алгоритм по умолчанию - Round Robin
        server host.docker.internal:3000 max_fails=2 fail_timeout=30s;
        server host.docker.internal:3001 max_fails=2 fail_timeout=30s;
        
        # Резервный сервер
        server host.docker.internal:3002 backup;
    }

    server {
        listen 80;

        location / {
            # Проксирование запросов к группе backend_servers
            proxy_pass http://backend_servers;
            
            # Передача заголовков для корректной работы
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
